name: fortran-vars
version: 0.3.0
synopsis: Fortran memory model and other static analysis tools.
description: Various Fortran static analysis tools focusing on a memory model for Fortran types. Uses fortran-src for the syntax representation.
category: Language
github: camfort/fortran-vars
license: Apache-2.0
maintainer: thefirstmuffinman@gmail.com

default-extensions:
- LambdaCase
- TypeApplications

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >=4.7 && <5
- fortran-src ^>= 0.10.2
- text >=1.2.2.2
- bytestring >=0.10.8.1
- containers >=0.5.7.1
- uniplate >=1.6.10
- aeson >=1.5.0.0
- fgl >=5
- deepseq >=1.4.4.0
- fortran-src-extras ^>= 0.3.1

library:
  source-dirs: src

executables:
  fortran-vars:
    source-dirs: app
    main: Main.hs
    dependencies:
    - fortran-vars
    ghc-options:
    - -threaded
    - -rtsopts

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    build-tools:
    - hspec-discover
    dependencies:
    - fortran-vars
    - hspec
    - HUnit
    ghc-options:
    - -threaded
    - -rtsopts
