name: fortran-vars
version: 0.3.1
synopsis: Fortran memory model and other static analysis tools.
description: Various Fortran static analysis tools focusing on a memory model for Fortran types. Uses fortran-src for the syntax representation.
category: Language
github: camfort/fortran-vars
license: Apache-2.0
maintainer: thefirstmuffinman@gmail.com

extra-source-files:
- README.md
- CHANGELOG.md

# raehik's extensions (GHC 9.2; last updated: 2022-08-17)
default-extensions:
# syntax that should be default
- EmptyCase
- LambdaCase
- InstanceSigs
- BangPatterns
- ExplicitNamespaces # 7.6

## deriving-related
- DerivingStrategies # 8.2
#- DerivingVia # 8.6
- StandaloneDeriving
- DeriveAnyClass
- DeriveGeneric
- DeriveDataTypeable
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveLift

# features that should be default
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses
- GADTs
- PolyKinds
- RoleAnnotations # 7.8
- RankNTypes

# other features
- TypeApplications # 8.0
- DefaultSignatures
- TypeFamilies
- DataKinds

# other syntax
- MagicHash
#- ImportQualifiedPost # 8.10
#- StandaloneKindSignatures # 8.10
- BinaryLiterals # 7.10

# essential, but can break things, so be wary
- ScopedTypeVariables # changes type var scoping quite dramatically
- TypeOperators # interferes with the old `*` type

# useful extensions to know about, but which must be specified on-demand
#- UndecidableInstances

ghc-options:
- -Wall

dependencies:
- base >=4.7 && <5
- fortran-src ^>= 0.10.2
- text >=1.2.2.2
- bytestring >=0.10.8.1
- containers >=0.5.7.1
- uniplate >=1.6.10
- aeson >=1.5.0.0
- fgl >=5
- deepseq >=1.4.4.0
- fortran-src-extras ^>= 0.3.1

library:
  source-dirs: src

executables:
  fortran-vars:
    source-dirs: app
    main: Main.hs
    dependencies:
    - fortran-vars
    ghc-options:
    - -threaded
    - -rtsopts

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    build-tools:
    - hspec-discover
    dependencies:
    - fortran-vars
    - hspec
    - HUnit
    ghc-options:
    - -threaded
    - -rtsopts
