resolver: lts-19.20
packages:
- '.'
save-hackage-creds: false

extra-deps:
#- fortran-src-0.10.2
- git: https://github.com/camfort/fortran-src
  commit: 1251b4ecc3259fd0ec16a38b2fcf17b062452b81
- fortran-src-extras-0.3.1
- yaml-0.11.8.0
