resolver: lts-19.20
packages:
- '.'
save-hackage-creds: false

extra-deps:
#- fortran-src-0.10.2
- git: https://github.com/camfort/fortran-src
  commit: 2efac302729a509c28ebe038d976681128e28804
- fortran-src-extras-0.3.1
- yaml-0.11.8.0
